name: fibonacci-cpp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: make fibonacci
      run: make fibonacci 
      
    - name: fibonacci30
      run: ./fibonacci 30
      
    - name: make test
      run: make test
      
    - name: TestResults
      run: cat TestResults.xml 
      
    - name: make googletest
      run: make googletest
      
    - name: make clean
      run: make clean
      

