name: fibonacci-cpp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: $PATH
    - run: echo $PATH
    - name: configure
      run: ./configure --prefix=$HOME
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
