name: fibonacci-cpp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses : actions/checkout@v2 
    
    - run : pip install pytest
    
    - run : python python/maths/fibonacci.py 30
    
    - run : pytest python/maths/tests/test_fibonacci.py 
